CREATE TABLE Ch04_1
(id	INTEGER		NOT NULL,
 name	VARCHAR(10)	,
 PRIMARY KEY (id));

BEGIN TRANSACTION;

INSERT INTO Ch04_1 VALUES (1, 'a');
INSERT INTO Ch04_1 VALUES (2, NULL);
INSERT INTO Ch04_1 VALUES (3, 'b');

COMMIT;

SELECT * FROM Ch04_1
 ORDER BY name;
