CREATE TABLE Salaries
(name	VARCHAR(10)	NOT NULL,
 salary	INTEGER		NOT NULL,
 PRIMARY KEY (name)
);

BEGIN TRANSACTION;

INSERT INTO Salaries VALUES ('相田', 300000);
INSERT INTO Salaries VALUES ('神崎', 270000);
INSERT INTO Salaries VALUES ('木村', 220000);
INSERT INTO Salaries VALUES ('斉藤', 290000);

COMMIT;
