CREATE TABLE ArrayTbl
(key	CHAR(1)		NOT NULL,
 i	INTEGER		NOT NULL,
 val	INTEGER		,
 PRIMARY KEY (key, i));

BEGIN TRANSACTION;

INSERT INTO ArrayTbl VALUES ('A', 1, NULL);
INSERT INTO ArrayTbl VALUES ('A', 2, NULL);
INSERT INTO ArrayTbl VALUES ('A', 3, NULL);
INSERT INTO ArrayTbl VALUES ('A', 4, NULL);
INSERT INTO ArrayTbl VALUES ('A', 5, NULL);
INSERT INTO ArrayTbl VALUES ('A', 6, NULL);
INSERT INTO ArrayTbl VALUES ('A', 7, NULL);
INSERT INTO ArrayTbl VALUES ('A', 8, NULL);
INSERT INTO ArrayTbl VALUES ('A', 9, NULL);
INSERT INTO ArrayTbl VALUES ('A', 10, NULL);

INSERT INTO ArrayTbl VALUES ('B', 1, 3);
INSERT INTO ArrayTbl VALUES ('B', 2, NULL);
INSERT INTO ArrayTbl VALUES ('B', 3, NULL);
INSERT INTO ArrayTbl VALUES ('B', 4, NULL);
INSERT INTO ArrayTbl VALUES ('B', 5, NULL);
INSERT INTO ArrayTbl VALUES ('B', 6, NULL);
INSERT INTO ArrayTbl VALUES ('B', 7, NULL);
INSERT INTO ArrayTbl VALUES ('B', 8, NULL);
INSERT INTO ArrayTbl VALUES ('B', 9, NULL);
INSERT INTO ArrayTbl VALUES ('B', 10, NULL);

INSERT INTO ArrayTbl VALUES ('C', 1, 1);
INSERT INTO ArrayTbl VALUES ('C', 2, 1);
INSERT INTO ArrayTbl VALUES ('C', 3, 1);
INSERT INTO ArrayTbl VALUES ('C', 4, 1);
INSERT INTO ArrayTbl VALUES ('C', 5, 1);
INSERT INTO ArrayTbl VALUES ('C', 6, 1);
INSERT INTO ArrayTbl VALUES ('C', 7, 1);
INSERT INTO ArrayTbl VALUES ('C', 8, 1);
INSERT INTO ArrayTbl VALUES ('C', 9, 1);
INSERT INTO ArrayTbl VALUES ('C', 10, 1);

INSERT INTO ArrayTbl VALUES ('D', 1, NULL);
INSERT INTO ArrayTbl VALUES ('D', 2, 9);
INSERT INTO ArrayTbl VALUES ('D', 3, NULL);
INSERT INTO ArrayTbl VALUES ('D', 4, NULL);
INSERT INTO ArrayTbl VALUES ('D', 5, NULL);
INSERT INTO ArrayTbl VALUES ('D', 6, NULL);
INSERT INTO ArrayTbl VALUES ('D', 7, NULL);
INSERT INTO ArrayTbl VALUES ('D', 8, NULL);
INSERT INTO ArrayTbl VALUES ('D', 9, NULL);
INSERT INTO ArrayTbl VALUES ('D', 10, NULL);

INSERT INTO ArrayTbl VALUES ('E', 1, NULL);
INSERT INTO ArrayTbl VALUES ('E', 2, 3);
INSERT INTO ArrayTbl VALUES ('E', 3, 1);
INSERT INTO ArrayTbl VALUES ('E', 4, 9);
INSERT INTO ArrayTbl VALUES ('E', 5, NULL);
INSERT INTO ArrayTbl VALUES ('E', 6, NULL);
INSERT INTO ArrayTbl VALUES ('E', 7, 9);
INSERT INTO ArrayTbl VALUES ('E', 8, NULL);
INSERT INTO ArrayTbl VALUES ('E', 9, NULL);
INSERT INTO ArrayTbl VALUES ('E', 10, NULL);

COMMIT;
