CREATE TABLE SeqTbl
(seq		INTEGER		NOT NULL,
 name		VARCHAR(10)	NOT NULL,
 PRIMARY KEY (seq));

BEGIN TRANSACTION;

INSERT INTO SeqTbl VALUES (1, 'ディック');
INSERT INTO SeqTbl VALUES (2, 'アン');
INSERT INTO SeqTbl VALUES (3, 'ライル');
INSERT INTO SeqTbl VALUES (5, 'カー');
INSERT INTO SeqTbl VALUES (6, 'マリー');
INSERT INTO SeqTbl VALUES (8, 'ベン');

COMMIT;
